#!/usr/bin/env bash
set -euo pipefail
# test-setup.sh — Verify forge-core generated setup
# Generated by forge-core v5.0.0 on 2026-03-07

echo "🧪 forge-core Setup Verification"
echo "=============================="
PASS=0; FAIL=0

check_cmd() {
  if "$@" >/dev/null 2>&1; then
    echo "  ✅ $1"; ((++PASS))
  else
    echo "  ❌ $1"; ((++FAIL))
  fi
}

check_file() {
  if [[ -f "$1" ]]; then
    echo "  ✅ $2 exists"; ((++PASS))
  else
    echo "  ❌ $2 missing"; ((++FAIL))
  fi
}

check_test() {
  if [[ $1 == "true" ]]; then
    echo "  ✅ $2"; ((++PASS))
  else
    echo "  ❌ $2"; ((++FAIL))
  fi
}

echo ""; echo "Platform:"
check_cmd bash --version
check_cmd git --version

echo ""; echo "Scripts:"
for s in .claude/scripts/*.sh; do
  [ -f "$s" ] || continue
  name=$(basename "$s")
  check_test "$(test -x "$s" && echo true || echo false)" "$name executable"
  check_cmd bash -n "$s"
  check_test "$(! file "$s" | grep -q CRLF && echo true || echo false)" "$name line endings"
done

echo ""; echo "=============================="
echo "Results: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ] && echo "✅ All passed" || echo "❌ $FAIL checks failed"
exit "$FAIL"
